import type { Metadata } from "next";
import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { cookies } from "next/headers";

const vazirmatn = Vazirmatn({
  subsets: ["latin"],
  variable: "--font-Vazirmatn"
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-Inter"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookiesInfo = await cookies();
  const locale= cookiesInfo.get('locale')?.value || 'en';
  const isrifgtToleft = locale === 'fa' || locale === 'pa';
  return (
  
  
      <html
       lang={locale}
       dir={locale==='en'? 'ltr': 'rtl'} suppressHydrationWarning
        className={`${locale==='en'?inter.variable:vazirmatn.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider >
          {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
